config/routes.rb
Karto::Application.routes.draw do
  resources :directories do
    resources :directories
    resources :leafs
    resources :lassos do
      member do
        post 'acquire'
      end 
    end
  end

  resources :leafs
  resources :lassos do
    resources :lassos do
      member do
        post 'detach'
      end 
    end 
    resources :leafs do
      member do
        post 'detach'
      end 
    end 
  end 

  get "welcome/index"

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

  root :to => 'welcome#index'

end

app/views/shared/_p_category_show.html.erb
<div>
	<div class="row">
		<%= render :partial => "shared/p_pins_show", :locals => {:directory => @directory, :favs => @favs, :pins => @pins } %>		
		<div class="span9">
			<div class="row">
				<ul class="breadcrumb">
					<li><%= link_to raw('<i class="icon-home"></i> Accueil'), root_path, :class => directory.parent.nil? ? "active" : "enabled" %>
						</li>
					<% dir = directory.parent %>
					<% out = "" %>
					<% while (! dir.nil?) && (! dir.parent.nil?)do %>
						<% out = '<li><span class="divider">/</span>'+link_to(h(dir.hr), dir)+'</li>' + out %>
						<% dir = dir.parent %>
					<% end %>	
					<%= raw(out) %>
					<% unless directory.parent.nil? %>
						<li class="active"><span class="divider">/</span><%= link_to h(directory.hr), directory %></li>
					<% end %>	
		    	</ul>
		    </div>	
		    <div class="row">
				<div class="span3">
					<div>
			    		<span class="label label-info"><i class="icon-folder-open icon-white"></i> <%= directory.name %>
						<%= link_to raw(' <i class="icon-edit icon-white"></i>'), [:edit, directory] %></span>
			    	</div>
					<div>
						<span class="label">créé le <%= directory.created_at.strftime("%e-%m-%y %H:%M") %>
						<% unless directory.created_at == directory.updated_at %>
							<br/>modif. le <%= directory.updated_at.strftime("%e-%m-%y %H:%M") %>
						<% end %>	
						</span>
					</div>
				</div>	 
			    <div class="span6">  
			      <strong><%= directory.note %></strong>
			    </div>		    
		    </div>
		    <div class="row">
				<div class="span4">
					<table class="table table-bordered table-striped table-condensed table-hover">
					    <thead>
					    	<tr>
						        <th><%= directory.hr %></th>
					    	</tr>
					    </thead>
					    <tbody>
							<% directory.directories.each do |dir| %>
							<tr>
								<td>
									<%= link_to raw('<i class="icon-folder-open"></i> '+h(dir.hr)), dir %> <%= link_to raw('<i class="icon-star'+(dir.fav ? "" : "-empty")+'"></i>'), directory_path(dir, "directory[fav]" => ! dir.fav), :method => :put %> <%= link_to raw('<i class="icon-tag'+(dir.pin ? "s" : "")+'"></i>'), directory_path(dir, "directory[pin]" => ! dir.pin), :method => :put %>
								</td>
							</tr>	
							<% end %>
					    </tbody>
					</table>
				</div>	
				<div class="span5">
					<table class="table table-bordered table-striped table-condensed table-hover">
					    <thead>
					    	<tr>
						        <th>Contenu</th>
					    	</tr>
					    </thead>
					    <tbody>
							<% directory.leafs.each do |leaf| %>
							<tr>
								<td><i class="icon-leaf"></i> <%= link_to leaf.hr, leaf %> <%= link_to raw('<i class="icon-star'+(leaf.fav ? "" : "-empty")+'"></i>'), leaf_path(leaf, "leaf[fav" => ! leaf.fav), :method => :put %> <%= link_to raw('<i class="icon-tag'+(leaf.pin ? "s" : "")+'"></i>'), leaf_path(leaf, "leaf[pin" => ! leaf.pin), :method => :put %></td>
							</tr>	
							<% end %>
							<% directory.lassos.each do |lasso| %>
							<tr>
								<td><i class="icon-briefcase"></i> <%= link_to lasso.hr, lasso %> <%= link_to raw('<i class="icon-star'+(lasso.fav ? "" : "-empty")+'"></i>'), lasso_path(lasso, "lasso[fav" => ! lasso.fav), :method => :put %> <%= link_to raw('<i class="icon-tag'+(lasso.pin ? "s" : "")+'"></i>'), lasso_path(lasso, "lasso[pin" => ! lasso.pin), :method => :put %></td>
							</tr>	
							<% end %>
					    </tbody>
					</table>
				</div>	
		    </div>	
		</div>	
	</div>	
</div>	

app/views/shared/_p_collector_form.html.erb
<div class="form-vertical well">
	<%= form_for [parent, collector], :action => collector.id.blank? ? "create" : "update"  do |f| %>
		<fieldset>
			<legend><%= collector.id.blank? ? "Nouveau fichier" : "Modification du fichier #{collector.name}"%></legend>
			<div class="control-group">
				<label class="control-label" for="input01">Nom</label>
				<div class="controls">
					<%= f.text_field :name, :class => "input-xlarge" %></br>
					<p class="help-block">Ce code mnémonique est plus pratique que le nom complet.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="input01">Description</label>
				<div class="controls">
					<%= f.text_field :hr, :class => "input-xlarge" %></br>
					<p class="help-block">Description courte.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="textarea">Description longue</label>
				<div class="controls">
					<%= f.text_area :note, :class => "input-xlarge" %>
				</div>
			</div>
			<div class="validation-error"></div>
			<div class="form-actions">
				<%= f.submit "Valider", :class => "btn btn-primary", :id => "new-item" %>
				<%= link_to "Annuler", parent %>
			</div>
		</fieldset>
	<% end %>
</div>

app/views/shared/_p_directory_form.html.erb
<div class="form-vertical well">
	<%= form_for directory,  :action => directory.id.blank? ? "create" : "update"  do |f| %>
		<fieldset>
			<legend><%= directory.id.blank? ? "Nouveau répertoire" : "Modification du répertoire #{directory.name}"%></legend>
			<div class="control-group">
				<label class="control-label" for="input01">Nom</label>
				<div class="controls">
					<%= f.text_field :name, :class => "input-xlarge" %></br>
					<p class="help-block">Ce code mnémonique est plus pratique que le nom complet.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="input01">Description</label>
				<div class="controls">
					<%= f.text_field :hr, :class => "input-xlarge" %></br>
					<p class="help-block">Description courte.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="textarea">Description longue</label>
				<div class="controls">
					<%= f.text_area :note, :class => "input-xlarge" %>
				</div>
			</div>
			<div class="validation-error"></div>
			<div class="form-actions">
				<%= f.submit "Valider", :class => "btn btn-primary", :id => "new-item" %>
				<%= link_to "Annuler", root_path %>
			</div>
		</fieldset>
	<% end %>
</div>

app/views/shared/_p_lasso_form.html.erb
<div class="form-vertical well">
	<%= form_for [parent, lasso], :action => lasso.id.blank? ? "create" : "update"  do |f| %>
		<fieldset>
			<legend><%= lasso.id.blank? ? "Nouveau fichier" : "Modification du fichier #{lasso.name}"%></legend>
			<div class="control-group">
				<label class="control-label" for="input01">Nom</label>
				<div class="controls">
					<%= f.text_field :name, :class => "input-xlarge" %></br>
					<p class="help-block">Ce code mnémonique est plus pratique que le nom complet.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="input01">Description</label>
				<div class="controls">
					<%= f.text_field :hr, :class => "input-xlarge" %></br>
					<p class="help-block">Description courte.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="textarea">Description longue</label>
				<div class="controls">
					<%= f.text_area :note, :class => "input-xlarge" %>
				</div>
			</div>
			<div class="validation-error"></div>
			<div class="form-actions">
				<%= f.submit "Valider", :class => "btn btn-primary", :id => "new-item" %>
				<%= link_to "Annuler", parent %>
			</div>
		</fieldset>
	<% end %>
</div>

app/views/shared/_p_lasso_show.html.erb
<div>
	<div class="row">
		<%= render :partial => "shared/p_pins_show", :locals => {:directory => lasso.directory, :favs => @favs, :pins => @pins } %>		
		<div class="span9">
			<div class="row">
				<ul class="breadcrumb">
					<li><%= link_to raw('<i class="icon-home"></i> Accueil'), root_path, :class => lasso.directory.parent.nil? ? "active" : "enabled" %><span class="divider">/</span></li>
					<% dir = lasso.directory.parent %>
					<% out = "" %>
					<% while (! dir.nil?) && (! dir.parent.nil?)do %>
						<% out = '<li>'+link_to(h(dir.hr), dir)+'<span class="divider">/</span></li>' + out %>
						<% dir = dir.parent %>
					<% end %>	
					<%= raw(out) %>
					<% unless lasso.directory.parent.nil? %>
						<li class="active"><%= link_to h(lasso.directory.hr), lasso.directory.parent %><span class="divider">/</span></li>
					<% end %>	
		    	</ul>
		    </div>	
		    <div class="row">
			      <h3><%= lasso.hr %></h3>
		    </div>
		    <div class="row">
				<div class="span3">
					<div>
			    		<span class="label label-info"><i class="icon-briefcase icon-white"></i> <%= lasso.name %>
						<%= link_to raw(' <i class="icon-edit icon-white"></i>'), [:edit, lasso.directory, lasso] %></span>
			    	</div>
					<div>
						<span class="label">créé le <%= lasso.created_at.strftime("%e-%m-%y %H:%M") %>
						<% unless lasso.created_at == lasso.updated_at %>
							<br/>modif. le <%= lasso.updated_at.strftime("%e-%m-%y %H:%M") %>
						<% end %>	
						</span>
					</div>
				</div>	 
			    <div class="span6">  
			      <%= raw(RedCloth.new(lasso.note).to_html) unless lasso.note.blank? %>
			    </div>	
			    <div>
			    	<span class="label label-info">
			    	<%= link_to raw(' <i class="icon-user icon-white"></i>'), [:acquire, lasso.directory, lasso], :method => :post %>
			    	</span>
			    </div>	    
		    </div>
		    <div class="row">
				<table class="table table-bordered table-striped table-hover">
				    <thead>
				      <tr>
				        <th>#</th>
				        <th>Nom</th>
				        <th>Description</th>
				        <th></th>
				      </tr>
				    </thead>
				    <tbody>
					<% lasso.children.each do |l| %>
						<tr>
					    	<td><%= l.id %></td>
					    	<td><%= l.name %></td>
					    	<td><%= l.hr %></td>
					    	<td><%= link_to raw(' <i class="icon-remove"></i>'), [:detach, lasso, l], :method => :post %></td>
						</tr>
					<% end %>
					<% lasso.leafs.each do |l| %>
						<tr>
					    	<td><%= l.id %></td>
					    	<td><%= l.name %></td>
					    	<td><%= l.hr %></td>
					    	<td><%= link_to raw(' <i class="icon-remove"></i>'), [:detach, lasso, l], :method => :post %></td>
						</tr>
					<% end %>
					</tbody>
				</table>
		    </div>	
		</div>	
	</div>	
</div>	

app/views/shared/_p_leaf_form.html.erb
<div class="form-vertical well">
	<%= form_for [parent, leaf], :action => leaf.id.blank? ? "create" : "update"  do |f| %>
		<fieldset>
			<legend><%= leaf.id.blank? ? "Nouveau fichier" : "Modification du fichier #{leaf.name}"%></legend>
			<div class="control-group">
				<label class="control-label" for="input01">Nom</label>
				<div class="controls">
					<%= f.text_field :name, :class => "input-xlarge" %></br>
					<p class="help-block">Ce code mnémonique est plus pratique que le nom complet.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="input01">Description</label>
				<div class="controls">
					<%= f.text_field :hr, :class => "input-xlarge" %></br>
					<p class="help-block">Description courte.</p>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="textarea">Description longue</label>
				<div class="controls">
					<%= f.text_area :note, :class => "input-xlarge" %>
				</div>
			</div>
			<div class="validation-error"></div>
			<div class="form-actions">
				<%= f.submit "Valider", :class => "btn btn-primary", :id => "new-item" %>
				<%= link_to "Annuler", parent %>
			</div>
		</fieldset>
	<% end %>
</div>

app/views/shared/_p_leaf_show.html.erb
<div>
	<div class="row">
		<%= render :partial => "shared/p_pins_show", :locals => {:directory => leaf.directory, :favs => @favs, :pins => @pins } %>		
		<div class="span9">
			<div class="row">
				<ul class="breadcrumb">
					<li><%= link_to raw('<i class="icon-home"></i> Accueil'), root_path, :class => leaf.directory.parent.nil? ? "active" : "enabled" %><span class="divider">/</span></li>
					<% dir = leaf.directory.parent %>
					<% out = "" %>
					<% while (! dir.nil?) && (! dir.parent.nil?)do %>
						<% out = '<li>'+link_to(h(dir.hr), dir)+'<span class="divider">/</span></li>' + out %>
						<% dir = dir.parent %>
					<% end %>	
					<%= raw(out) %>
					<% unless leaf.directory.parent.nil? %>
						<li class="active"><%= link_to h(leaf.directory.hr), leaf.directory.parent %><span class="divider">/</span></li>
					<% end %>	
		    	</ul>
		    </div>	
		    <div class="row">
			      <h3><%= leaf.hr %></h3>
		    </div>
		    <div class="row">
				<div class="span3">
					<div>
						<span class="label label-info"><i class="icon-leaf icon-white"></i> <%= leaf.name %>
						<%= link_to raw(' <i class="icon-edit icon-white"></i>'), [:edit, leaf.directory, leaf] %></span>
					</div>
					<div>
						<span class="label">créé le <%= leaf.created_at.strftime("%e-%m-%y %H:%M") %>
						<% unless leaf.created_at == leaf.updated_at %>
							<br/>modif. le <%= leaf.updated_at.strftime("%e-%m-%y %H:%M") %>
						<% end %>	
						</span>
					</div>	 
			    </div>
			    <div class="span6">  
			      <strong><%= leaf.note %></strong>
			    </div>		    
		    </div>
		    <div class="row">
				<table class="table table-bordered table-striped table-hover">
				    <thead>
				      <tr>
				        <th>#</th>
				        <th>Nom</th>
				        <th>Description</th>
				        <th></th>
				      </tr>
				    </thead>
				    <tbody>
					<% leaf.lassos.each do |l| %>
						<tr>
					    	<td><%= l.id %></td>
					    	<td><%= l.name %></td>
					    	<td><%= l.hr %></td>
					    	<td></td>
						</tr>
					<% end %>
					</tbody>
				</table>
		    </div>	
		</div>	
	</div>	
</div>	

app/views/shared/_p_pins_show.html.erb
<div class="span3">
	<div class="" style="padding: 8px 0;">
        <ul class="nav nav-list">
			<li class="nav-header"><i class="icon-plus"></i> Ajouts</li>
			<li><%= link_to "Répertoire", new_directory_directory_path(directory) %></li>
			<li><%= link_to "Fichier", new_directory_leaf_path(directory) %></li>
			<li><%= link_to "Collecteur", new_directory_lasso_path(directory) %></li>
			<li class="divider"></li>
			<li class="nav-header"><i class="icon-tags"></i> Favoris</li>
			<% favs[0].each do |dir| %>
				<li><%= link_to raw('<i class="icon-folder-open"></i> '+h(dir.hr)), dir %></li>
			<% end %>
			<% favs[1].each do |col| %>
				<li><%= link_to raw('<i class="icon-briefcase"></i> '+h(col.hr)), col %></li>
			<% end %>
			<% favs[2].each do |leaf| %>
				<li><%= link_to raw('<i class="icon-leaf"></i> '+h(leaf.hr)), leaf %></li>
			<% end %>
			<li class="divider"></li>
			<li class="nav-header"><i class="icon-tags"></i> Lots</li>
			<% pins[0].each do |dir| %>
				<li><%= link_to raw('<i class="icon-folder-open"></i> '+h(dir.hr)), dir %></li>
			<% end %>
			<% pins[1].each do |col| %>
				<li><%= link_to raw('<i class="icon-briefcase"></i> '+h(col.hr)), col %></li>
			<% end %>
			<% pins[2].each do |leaf| %>
				<li><%= link_to raw('<i class="icon-leaf"></i> '+h(leaf.hr)), leaf %></li>
			<% end %>
        </ul>
    </div>	
</div>    